name: preview
on: pull_request

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          env: 
            API_KEY: ${{ vars.API_KEY }}
            AUTH_DOMAIN: ${{ vars.AUTH_DOMAIN }}
            DATABASE_URL: ${{ vars.DATABASE_URL }}
            PROJECT_ID: ${{ vars.PROJECT_ID }}
            STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
            MESSAGING_SENDER_ID: ${{ vars.MESSAGING_SENDER_ID }}
            APP_ID: ${{ vars.APP_ID }}
          command: eas update --auto
